http:
  middlewares:
    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          CrowdsecLapiKey: "{{env "BOUNCER_KEY_TRAEFIK"}}"
          Enabled: "true"
          CrowdsecLapiScheme: "http"
          CrowdsecLapiHost: "crowdsec:8080"
