# https://plugins.traefik.io/plugins/628c9ebcffc0cd18356a979f/fail2-ban
http:
  middlewares:
    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          CrowdsecLapiKey: "{{env "BOUNCER_KEY_TRAEFIK"}}"
          Enabled: "true"
          CrowdsecLapiScheme: "http"
          CrowdsecLapiHost: "crowdsec:8080"
